---
# Node Exporter Configuration Variables

# Service description
node_exporter_description: "Prometheus Node Exporter"

# Service name (used for systemd service name)
node_exporter_service_name: "node-exporter"

# User and group for the service
node_exporter_user: "node-exporter"
node_exporter_group: "node-exporter"

# Version and download
node_exporter_version: "1.6.1"
node_exporter_release_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

# Paths
node_exporter_install_dir: "/opt/node-exporter"
node_exporter_tmp_dir: "/tmp"
node_exporter_archive: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_extract_dir: "{{ node_exporter_tmp_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64"

# Service port
node_exporter_port: 9100
