---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Python and pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Create mock service user
  ansible.builtin.user:
    name: "{{ mock_service_user }}"
    system: yes
    shell: /bin/false
    home: "{{ mock_service_working_dir }}"
    create_home: no

- name: Create mock service directory
  ansible.builtin.file:
    path: "{{ mock_service_working_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ mock_service_user }}"
    group: "{{ mock_service_group }}"

- name: Copy mock service script
  ansible.builtin.copy:
    src: mock_service.py
    dest: "{{ mock_service_script_path }}"
    mode: '0755'
    owner: "{{ mock_service_user }}"
    group: "{{ mock_service_group }}"

- name: Ensure log file exists and is owned by mock-service user
  ansible.builtin.file:
    path: /var/log/mock-service.log
    state: touch
    owner: "{{ mock_service_user }}"
    group: "{{ mock_service_group }}"
    mode: '0644'

- name: Create systemd service file
  ansible.builtin.template:
    src: mock-service.service.j2
    dest: /etc/systemd/system/{{ mock_service_name }}.service
    mode: '0644'
  notify: restart mock-service

- name: Enable and start mock service
  ansible.builtin.systemd:
    name: "{{ mock_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
