# Playbook: monitoring_check.yml
# Purpose: Perform live health checks for all services across all nodes.
# Usage: ansible-playbook -i inventory/hosts.ini playbooks/monitoring_check.yml
---
- name: Health Check - Verify All Services
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if mock service is running (app servers)
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ mock_service_port | default(8080) }}"
        method: GET
        status_code: 200
      when: inventory_hostname in groups['app_servers']
      register: mock_service_check
      ignore_errors: yes

    - name: Check if MariaDB is running (database servers)
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ mariadb_port | default(3306) }}"
        timeout: 10
      when: inventory_hostname in groups['database_servers']

    - name: Check if Node Exporter is running
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:9100/metrics"
        method: GET
        status_code: 200
      when: inventory_hostname in groups['node_exporters']
      register: node_exporter_check
      ignore_errors: yes

    - name: Check if Prometheus is running (monitoring servers)
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ prometheus_port | default(9090) }}/api/v1/status/targets"
        method: GET
        status_code: 200
      when: inventory_hostname in groups['monitoring_servers']
      register: prometheus_check
      ignore_errors: yes

    - name: Check if Grafana is running (monitoring servers)
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ grafana_port | default(3000) }}/api/health"
        method: GET
        status_code: 200
      when: inventory_hostname in groups['monitoring_servers']
      register: grafana_check
      ignore_errors: yes

    - name: Display health check results
      ansible.builtin.debug:
        msg: |
          ===== Health Check Results for {{ inventory_hostname }} ({{ ansible_default_ipv4.address }}) =====
          {% if inventory_hostname in groups['app_servers'] %}
          Mock Service: {{ 'OK' if mock_service_check.status == 200 else 'FAILED' }}
          {% endif %}
          {% if inventory_hostname in groups['database_servers'] %}
          MariaDB: OK
          {% endif %}
          {% if inventory_hostname in groups['node_exporters'] %}
          Node Exporter: {{ 'OK' if node_exporter_check.status == 200 else 'FAILED' }}
          {% endif %}
          {% if inventory_hostname in groups['monitoring_servers'] %}
          Prometheus: {{ 'OK' if prometheus_check.status == 200 else 'FAILED' }}
          Grafana: {{ 'OK' if grafana_check.status == 200 else 'FAILED' }}
          {% endif %}
