# Playbook: setup_monitoring.yml
# Set up Prometheus and Grafana on all monitoring servers.
# Usage: ansible-playbook -i inventory/hosts.ini playbooks/setup_monitoring.yml
#
# Debug tasks in roles are tagged 'debug' and controlled by DEBUG environment variable.
# To run debug tasks: DEBUG=true ansible-playbook ... OR ansible-playbook ... --tags debug
# To skip debug tasks (default): ansible-playbook ... --skip-tags debug
---
- name: Setup Prometheus and Grafana on monitoring servers
  hosts: monitoring_servers
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/../group_vars/monitoring_servers/vault.yml"
  vars:
    # After loading vault.yml, assign the password variables
    grafana_admin_password: "{{ vault_grafana_admin_password }}"

  roles:
    - { role: prometheus, tags: ['prometheus'] }
    - { role: grafana, tags: ['grafana'] }

  post_tasks:
    - name: Wait for Prometheus to be available
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ prometheus_port }}"
        delay: 10
        timeout: 60
      tags: ['prometheus']

    - name: Wait for Grafana to be available
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ grafana_port }}"
        delay: 10
        timeout: 60
      tags: ['grafana']

    - name: Display service status
      ansible.builtin.debug:
        msg: |
          ===== Service Status for {{ inventory_hostname }} =====
          Prometheus: http://{{ ansible_default_ipv4.address }}:{{ prometheus_port }}
          Grafana: http://{{ ansible_default_ipv4.address }}:{{ grafana_port }}
      tags: ['status']
